routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('student.search');
});
Route::post('/search', [StudentController::class, 'search']);
Route::resource('student', 'App\Http\Controllers\StudentController');

app/Models/course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class course extends Model
{
    //use HasFactory;
    protected $primaryKey = 'course_id';
    protected $fillable=['course_id','name_thai','name_eng'];
}

app/Models/students.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class students extends Model
{
    //use HasFactory;
    protected $primaryKey = 'student_id';
    protected $fillable = ['student_id','first_name', 'last_name','course_id'];
    protected $foreignkey = 'course_id';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\students;
use App\Models\course;
use Illuminate\Support\Facades\DB;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = students::all()->toArray();
        return view('student.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name'    =>  'required',
            'last_name'     =>  'required',
            'course_id'     =>  'required'
        ]);
        $student = new students([
            'first_name'    =>  $request->get('first_name'),
            'last_name'     =>  $request->get('last_name'),
            'course_id'     =>  $request->get('course_id')
        ]);
        $student->save();
        return redirect()->route('student.create')->with('success', 'Data Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = students::find($id);
        return view('student.edit', compact('student', 'id'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'first_name'    =>  'required',
            'last_name'     =>  'required',
            'course_id'     =>  'required'
        ]);
        $student = students::find($id);
        $student->first_name = $request->get('first_name');
        $student->last_name = $request->get('last_name');
        $student->course_id = $request->get('course_id');
        $student->save();
        return view('student.search')->with('success', 'Data Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = students::find($id);
        $student->delete();
        return view('student.search')->with('success', 'Data Deleted');
    }

    public function search(Request $request){
        $course_id = $request->get('course_id');
       
        $result = DB::select( DB::raw("SELECT students.first_name,students.last_name,students.student_id,courses.name_thai,courses.name_eng
                                             FROM examfinal.students 
                                             INNER JOIN examfinal.courses
                                             ON(students.course_id=courses.course_id)
                                             WHERE students.course_id=$course_id"));
        $result = collect($result)->map(function($x){ return (array) $x; })->toArray();
        // dd($namethai);
        return view('student.index',compact('result'))->with('course_id',$course_id);
    }
}

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
    <title>@yield('title')</title>
</head>
<body>
    @yield('content')
</body>
<footer>
    @yield('footer')
</footer>
</html>

resources/views/student/create.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
  <div class="col-md-12">
    <br />
    <h3 align="center">Add Member</h3>
    <br />

    @if(count($errors) > 0)
    <div class="alert alert-danger">
    <ul>
    @foreach($errors->all() as $error)
        <li>{{$error}}</li>
    @endforeach
    </ul>
    </div>
    @endif

    @if(\Session::has('success'))
    <div class="alert alert-success">
    <p>{{ \Session::get('success') }}</p>
    </div>
    @endif

    <form method="post" action="{{url('student')}}">
        {{csrf_field()}}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                    <div class="form-group">
                        <input type="text" name="first_name" class="form-control" placeholder="Enter First Name" />
                    </div>
            </div>
            <div class="col-md-4"></div>
        </div>

        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                    <div class="form-group">
                        <input type="text" name="last_name" class="form-control" placeholder="Enter Last Name" />
                    </div>
            </div>
            <div class="col-md-4"></div>
        </div>

        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                    <div class="form-group">
                        <input type="text" name="course_id" class="form-control" placeholder="Enter course id" />
                    </div>
            </div>
            <div class="col-md-4"></div>
        </div>

        <div align="right" style="padding-right: 400px;">
                <div class="form-group">
                    <input type="submit"value="Create" class="btn btn-success" />&nbsp;
                    <a href="{{url('/')}}" class="btn btn-primary">Go to Search</a>
                </div>
            <br />
            <br />
        </div>
    </form>
 </div>
</div>
@endsection

resources/views/student/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
  <div class="col-md-12">
       <br />
       <h3 align="center">Edit Data of Member</h3>
       <br />
       @if(count($errors) > 0)

       <div class="alert alert-danger">
              <ul>
              @foreach($errors->all() as $error)
              <li>{{$error}}</li>
              @endforeach
              </ul>
       @endif
       <form method="post" action="{{ route('student.update', $id)}}">
              {{csrf_field()}}
              <input type="hidden" name="_method" value="PATCH" />
              <div class="row">
                     <div class="col-md-3"></div>
                     <div class="col-md-6">
                            <div class="form-group">
                                   <input type="text" name="first_name" class="form-control" value="{{$student->first_name}}" placeholder="Enter First Name" />
                            </div>
                     </div>
                     <div class="col-md-4"></div>
              </div>

              <div class="row">
                     <div class="col-md-3"></div>
                     <div class="col-md-6">
                            <div class="form-group">
                                   <input type="text" name="last_name" class="form-control" value="{{$student->last_name}}" placeholder="Enter Last Name" />
                            </div>
                     </div>
                     <div class="col-md-4"></div>
              </div>

              <div class="row">
                     <div class="col-md-3"></div>
                     <div class="col-md-6">
                            <div class="form-group">
                                   <input type="text" name="course_id" class="form-control" value="{{$student->course_id}}" placeholder="Enter course id" />
                            </div>
                     </div>
                     <div class="col-md-4"></div>
              </div>

              <div align="right" style="padding-right: 400px;">
                     <div class="form-group">
                         <input type="submit" class="btn btn-warning" value="Edit" />&nbsp;
                         <a href="{{url('/')}}" class="btn btn-primary">Go to Search</a>
                     </div>
                 <br />
                 <br />
             </div>
       </form>
  </div>
</div>

@endsection

resources/views/student/index.blade.php
@extends('layouts.master')
@section('title','Web Programming')
@section('content')

<div class="row">
 <div class="col-md-12">
  <br />
 <h3 align="center">Member in Course</h3>
  <br />

  @if($message = Session::get('success'))
  <div class="alert alert-success">
   <p>{{$message}}</p>
  </div>
  @endif

  <div align="right" style="padding-right: 260px;">
        <a href="{{route('student.create')}}" class="btn btn-success">Add Members</a>
        <a href="{{url('/')}}" class="btn btn-primary" >Back to Search</a>
        <br />
        <br />
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <table class="table table-bordered table-striped table-dark">
        <tr>
            <th>Student ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Course Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        @foreach($result as $row)
        <tr>
            <td>{{$row['student_id']}}</td>
            <td>{{$row['first_name']}}</td>
            <td>{{$row['last_name']}}</td>
            <td>{{$row['name_thai']}}</td>
            <td>
                <a href="{{ route('student.edit', $row['student_id'])}}" class="btn btn-warning">Edit</a>
            </td>
            <td>
            <form method="post" class="delete_form" action="{{ route('student.destroy', $row['student_id'])}}">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="DELETE" />
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            </td>
        </tr>
        @endforeach
        </table>
    </div>
    <div class="col-md-2"></div>
  </div>
 </div>
</div>

<script>
$(document).ready(function(){
 $('.delete_form').on('submit', function(){
  if(confirm("Are you sure you want to delete it?")){  
    return true;  
  }
  else  { 
    return false;
  }
 });
});
</script>
@endsection

resources/views/student/search.blade.php
@extends('layouts.master')
@section('title','Web Programming')
@section('content')

<br><br>
    <h1 align="center">Search Course</h1><hr>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-6"><br>
        
        <form method="post" action="{{url('/search')}}" class="form-inline">
         {{ csrf_field() }}
                <div class="form-group"  style="margin-left:40px">
                    <lable>กรุณากรอกคอร์สเรียน : &nbsp;</lable>
                    <input type="text" name="course_id" class="form-control" placeholder="โปรดระบุรหัสคอร์สเรียน"/>
                </div>
            <input class="btn btn-primary" type="submit" name="search" value="ค้นหา" style="margin-left:10px"/>
        </form>
        </div>
    </div>
</div>
        
@endsection